# WSO2 Choreo/AMP Component Configuration
# This file is read during deployment to configure resource limits
# Place in .choreo/component.yaml or component.yaml in repo root

apiVersion: core.choreo.dev/v1beta1
kind: Component
spec:
  # Component metadata
  displayName: "Finance Insight Service"
  description: "AI-powered finance research and analysis service"
  
  # Container configuration
  container:
    # Port the service listens on
    port: 8000
    
    # Health check endpoints
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    
    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    
    # Resource limits and requests
    resources:
      limits:
        cpu: "1000m"      # 1 CPU core
        memory: "1Gi"     # 1 GiB RAM
      requests:
        cpu: "500m"       # 0.5 CPU core
        memory: "768Mi"   # 768 MiB RAM minimum
  
  # Environment variables
  env:
    - name: CREWAI_TRACING_ENABLED
      value: "false"
    - name: FLASK_ENV
      value: "production"
