apiVersion: batch/v1
kind: CronJob
metadata:
  name: finance-memory-patcher
  namespace: dp-default-default-default-ccb66d74
spec:
  schedule: "*/2 * * * *"  # Every 2 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: patcher
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Checking memory limits..."
              CURRENT=$(kubectl get deployment finance-insight-default-965f1bd1 -o jsonpath='{.spec.template.spec.containers[0].resources.limits.memory}')
              if [ "$CURRENT" != "8Gi" ]; then
                echo "Patching from $CURRENT to 8Gi..."
                kubectl patch deployment finance-insight-default-965f1bd1 --type='json' -p='[
                  {"op": "replace", "path": "/spec/template/spec/containers/0/resources/limits/memory", "value": "8Gi"},
                  {"op": "replace", "path": "/spec/template/spec/containers/0/resources/limits/cpu", "value": "4000m"},
                  {"op": "replace", "path": "/spec/template/spec/containers/0/resources/requests/memory", "value": "2Gi"}
                ]'
                echo "Patched successfully"
              else
                echo "Memory already correct: $CURRENT"
              fi
          restartPolicy: OnFailure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-patcher
  namespace: dp-default-default-default-ccb66d74
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-patcher-binding
  namespace: dp-default-default-default-ccb66d74
subjects:
- kind: ServiceAccount
  name: default
  namespace: dp-default-default-default-ccb66d74
roleRef:
  kind: Role
  name: deployment-patcher
  apiGroup: rbac.authorization.k8s.io
